#!/usr/bin/env bash
#
# Regenerate the Xcode project, build a signed app, refresh icon caches, and
# launch it.
#
#   ./run.sh            # Debug build (default) — fast to compile, for iterating
#   ./run.sh release    # Release build — optimized; the "real" local build
#
# Always run this (or at least `xcodegen generate`) after a `git pull`: the
# .xcodeproj is generated by XcodeGen and is NOT committed, so newly added
# files (e.g. the icon assets) won't appear in a stale, previously-generated
# project — which shows up as a blank app icon and "No image named ... found
# in asset catalog" at runtime.
#
# SIGNING — why this matters for the media keys:
# Beamhook needs the Accessibility permission to install its media-key event
# tap. macOS binds that grant to the app's code-signing identity. An *ad-hoc*
# signed app ("-") has no stable identity, so its cdhash changes on every
# rebuild and macOS silently forgets the grant — the toggle still shows "on"
# but AXIsProcessTrusted() returns false, the tap never starts, and the media
# keys fall back to whatever the system wants (Safari/Music hijack them).
#
# So we sign with your real Apple Development identity (auto-detected from the
# login keychain) using MANUAL signing — that needs no Apple-ID login or
# provisioning profile, and produces a designated requirement based on the
# bundle id + certificate, which is identical across rebuilds. You grant
# Accessibility ONCE and it sticks. Override the identity with
# BEAMHOOK_SIGN_ID=<40-char hash or identity name> if needed.
#
set -euo pipefail
cd "$(dirname "$0")"

# Build configuration (Debug default; `./run.sh release` for an optimized build).
CONFIG="Debug"
case "${1:-}" in
  ""|debug|Debug)   CONFIG="Debug" ;;
  release|Release)  CONFIG="Release" ;;
  *) echo "usage: ./run.sh [debug|release]" >&2; exit 1 ;;
esac

command -v xcodegen >/dev/null 2>&1 || {
  echo "error: xcodegen not found. Install it with:  brew install xcodegen" >&2
  exit 1
}

# SHA-1 hash of the first usable code-signing identity, preferring an Apple
# Development cert (the kind Xcode creates for a free Apple ID).
detect_identity() {
  security find-identity -v -p codesigning 2>/dev/null \
    | grep -E 'Apple Development|Mac Developer|Developer ID Application|Apple Distribution' \
    | head -1 \
    | sed -n 's/^[[:space:]]*[0-9][0-9]*)[[:space:]]*\([0-9A-Fa-f]\{40\}\).*/\1/p'
}
SIGN_ID="${BEAMHOOK_SIGN_ID:-$(detect_identity)}"

echo "==> Regenerating Beamhook.xcodeproj"
xcodegen generate

if [ -n "$SIGN_ID" ]; then
  echo "==> Building ($CONFIG, signed with $SIGN_ID — Accessibility grant persists across rebuilds)"
  xcodebuild -project Beamhook.xcodeproj -scheme Beamhook -configuration "$CONFIG" \
    -derivedDataPath build \
    CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="$SIGN_ID" PROVISIONING_PROFILE_SPECIFIER="" \
    CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=YES \
    build
else
  echo "WARNING: no code-signing identity found in your keychain." >&2
  echo "         Falling back to AD-HOC signing. macOS will FORGET the Accessibility" >&2
  echo "         grant every time you rebuild, so the media keys will stop working" >&2
  echo "         until you re-grant. To fix permanently, add a free Apple ID in" >&2
  echo "         Xcode > Settings > Accounts (creates an 'Apple Development' identity)." >&2
  xcodebuild -project Beamhook.xcodeproj -scheme Beamhook -configuration "$CONFIG" \
    -derivedDataPath build \
    CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="-" \
    CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=YES \
    build
fi

# Ask the project for the product name rather than hardcoding it: everything
# except `Official` builds as Beamhookdev.app (see project.yml), and a stale
# guess here would point at the wrong bundle — or, worse, make the pkill below
# terminate an installed Beamhook.app instead of this build.
APP_NAME="$(xcodebuild -project Beamhook.xcodeproj -scheme Beamhook \
  -configuration "$CONFIG" -showBuildSettings 2>/dev/null \
  | awk -F' = ' '/ FULL_PRODUCT_NAME = /{print $2; exit}')"
APP_NAME="${APP_NAME:-Beamhookdev.app}"
APP="build/Build/Products/$CONFIG/$APP_NAME"

echo "==> Signature:"
codesign -dv "$APP" 2>&1 | grep -E 'Authority=Apple Development|Authority=Developer ID|Signature=|TeamIdentifier=' | sed 's/^/    /' || true

# Refresh macOS icon caches so a changed app icon shows up (no sudo needed).
# macOS caches app icons aggressively; without this the Dock/Finder can keep
# showing the previous icon after a rebrand.
echo "==> Refreshing icon caches"
touch "$APP"
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister"
[ -x "$LSREGISTER" ] && "$LSREGISTER" -f "$APP" >/dev/null 2>&1 || true
killall Dock >/dev/null 2>&1 || true

# Replace any already-running instance with the fresh build. Matched on this
# build's own executable name so an installed Beamhook.app is left alone.
pkill -x "${APP_NAME%.app}" >/dev/null 2>&1 || true
echo "==> Launching $APP"
open "$APP"
echo "Done. (If Finder still shows an old icon, run: killall Finder)"
