#!/usr/bin/env bash
#
# Regenerate the Xcode project, build an ad-hoc-signed Debug app, and launch it.
#
# Always run this (or at least `xcodegen generate`) after a `git pull`: the
# .xcodeproj is generated by XcodeGen and is NOT committed, so newly added
# files (e.g. the icon assets) won't appear in a stale, previously-generated
# project — which shows up as a blank app icon and "No image named ... found
# in asset catalog" at runtime.
#
set -euo pipefail
cd "$(dirname "$0")"

command -v xcodegen >/dev/null 2>&1 || {
  echo "error: xcodegen not found. Install it with:  brew install xcodegen" >&2
  exit 1
}

echo "==> Regenerating Beamhook.xcodeproj"
xcodegen generate

echo "==> Building (Debug, ad-hoc signed)"
xcodebuild -project Beamhook.xcodeproj -scheme Beamhook -configuration Debug \
  -derivedDataPath build \
  CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="-" \
  CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=YES \
  build

APP="build/Build/Products/Debug/Beamhook.app"

# Replace any already-running instance with the fresh build.
pkill -x Beamhook >/dev/null 2>&1 || true
echo "==> Launching $APP"
open "$APP"
echo "Done. Look for the play/pause icon in your menubar."
