import Foundation

/// Which menu-bar template image stands for the current hook. Raw values are
/// asset-catalog names, generated by `Icon/make-icons.sh` — keep the two in step.
///
/// Only the sources we ship art for get a badge; everything else falls back to
/// the plain hook, so an unrecognized or user-added app is never left blank.
public enum MenuBarGlyph: String, CaseIterable, Sendable {
    case hook = "MenuBarIcon"
    case safari = "MenuBarIcon-Safari"
    case chrome = "MenuBarIcon-Chrome"
    case youtube = "MenuBarIcon-YouTube"
    case spotify = "MenuBarIcon-Spotify"
    case appleMusic = "MenuBarIcon-AppleMusic"

    /// - Parameters:
    ///   - id: the hooked `AppDefinition` id, or nil when nothing is hooked.
    ///   - browserHost: hostname of the hooked browser tab. Callers pass this
    ///     only for browser targets, and only once a scan has identified the tab.
    ///
    /// A YouTube tab outranks the browser it is playing in: what the user is
    /// listening to is more useful at a glance than which browser holds it. That
    /// also gives Brave, Arc and Vivaldi a badge on YouTube even though they have
    /// no browser art of their own — they keep the plain hook otherwise, since
    /// borrowing Chrome's mark for a different browser would just be wrong.
    public static func forTarget(id: String?, browserHost: String? = nil) -> MenuBarGlyph {
        if let browserHost, isYouTube(host: browserHost) { return .youtube }
        switch id {
        case BuiltInApps.spotify.id: return .spotify
        case BuiltInApps.music.id: return .appleMusic
        case BuiltInApps.safariYouTube.id: return .safari
        case BuiltInApps.chromeYouTube.id: return .chrome
        default: return .hook
        }
    }

    /// Anchored so a lookalike domain such as `notyoutube.com` cannot match, and
    /// suffix-based so `music.youtube.com` and `m.youtube.com` both count.
    static func isYouTube(host: String) -> Bool {
        var host = host.lowercased()
        if host.hasSuffix(".") { host.removeLast() }        // fully-qualified form
        if host.hasPrefix("www.") { host.removeFirst(4) }
        return host == "youtube.com" || host.hasSuffix(".youtube.com") || host == "youtu.be"
    }
}
